name: SmartDeploy Application

on:
  push:
    tags:
      - 'v*'

jobs:
  manufacture-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch Source Code Repository
        uses: actions/checkout@v4

      - name: Extract Tag and Short Git Commit SHA
        id: meta
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "clean_tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Initialize Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Execute Makefile Package Routine
        run: |
          VERSION_STRING="${{ steps.meta.outputs.clean_tag }}-${{ steps.meta.outputs.sha_short }}"
          make package VERSION=$VERSION_STRING

      - name: Upload v1 Container Tarball Archive
        uses: actions/upload-artifact@v4
        with:
          name: smartdeploy-v1-package-${{ steps.meta.outputs.clean_tag }}
          path: smartdeploy-v1-${{ steps.meta.outputs.clean_tag }}-*.tar
          retention-days: 7

      - name: Upload v2 Container Tarball Archive
        uses: actions/upload-artifact@v4
        with:
          name: smartdeploy-v2-package-${{ steps.meta.outputs.clean_tag }}
          path: smartdeploy-v2-${{ steps.meta.outputs.clean_tag }}-*.tar
          retention-days: 7